---
include:
  - "**/*.rb"
exclude:
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths:
  - 'lib'
plugins: []
max_files: 5000

